version: "3.1"
services:
  pact_mock_service:
    build:
      context: .
      dockerfile: local/docker/Dockerfile
    volumes:
      - .:/app:cached
    entrypoint: "bash -c 'yarn run test:all'"
    ports:
      - 8281:8281
      - 9999:9999