service: pact-mock

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs12.x
  region: eu-west-2
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-webpack
  - 'serverless-offline'

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packager: "yarn"
  serverless-offline:
    location: .webpack/service

functions:
  pact_mock:
    name: pact-mock-${self:provider.stage}
    handler: src/functions/handler.handler
    # Uncomment this on deploy, serverless-offline fails otherwise
    layers:
      - ${cf:pact-standalone-${self:provider.stage}.PactStandaloneLayerExport}
    events:
      - http: ANY /{path+}