service: pact-mock

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs12.x
  region: eu-west-2
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-webpack
  - serverless-offline-pact
  - 'serverless-offline'

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packager: "yarn"
  serverless-offline:
    location: .webpack/service
  pact:
    stub:
      filePath: 'pact.json'
      noStart: true
      port: 9998
      stages:
        - local

functions:
  pact_mock:
    name: pact-mock-${self:provider.stage}
    handler: src/functions/lambda.run  # koa 
    # handler: src/functions/handler.run
    # Uncomment this on deploy, serverless-offline fails to start if it exists
    # layers:
    #   - ${cf:pact-standalone-${self:provider.stage}.PactStandaloneLayerExport}
    events:
      - http: ANY /{path+}